import random

leaveProgram = 0
while leaveProgram !="q":
    print("this is a dice rolling program")
    print("press enter to roll")
    input()
    number = random.randint(1,6)
    if number==1:
        print("[----------]")
        print("            ")
        print("      0     ")
        print("            ")
        print("[----------]")
        print()
        print("press q to quit")
        leaveProgram = input()
    if number==1:
        print("[----------]")
        print("            ")
        print("      0     ")
        print("            ")
        print("[----------]")
        print()
        print("press q to quit")
        leaveProgram = input()
    if number==2:
        print("[----------]")
        print("            ")
        print("     0 0    ")
        print("            ")
        print("[----------]")
        print()
        print("press q to quit")
        leaveProgram = input()
    if number==3:
        print("[----------]")
        print("            ")
        print("     000    ")
        print("            ")
        print("[----------]")
        print()
        print("press q to quit")
        leaveProgram = input()
    if number==4:
        print("[----------]")
        print("            ")
        print("      00    ")
        print("      00    ")
        print("[----------]")
        print()
        print("press q to quit")
        leaveProgram = input()
    if number==5:
        print("[----------]")
        print("     00     ")
        print("     000    ")
        print("            ")
        print("[----------]")
        print()
        print("press q to quit")
        leaveProgram = input()
    if number==6:
        print("[----------]")
        print("    000     ")
        print("    000     ")
        print("            ")
        print("[----------]")
        print()
        print("press q to quit")
        leaveProgram = input()
